# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ViperMoviesssDB' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ViperMoviesssDB
  pod 'Moya/RxSwift', '~> 13.0'

  target 'ViperMoviesssDBTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ViperMoviesssDBUITests' do
    # Pods for testing
  end

end
